### ISSUE TITLE
catch visitors

### ISSUE THREAD

**Issue by brbear** [lptracker/php-sdk#3]
Hello,

could you please tell me how I can get an information about 

"catching visitors" (захват посетителя)

with this api?

![zafv](https://user-images.githubusercontent.com/13675752/54602271-43fdf000-4a52-11e9-8071-f768ef3f2b51.jpg)

**Comment by sergeymakinen** [comment]
Hello, could you please explain what kind of information you need? Search leads by caught visitors? Or do you miss some info in a lead?
P. S. You can freely ask in Russian if you like. :)

**Comment by sergeymakinen** [comment]
Still no answer, closing for now.
