### ISSUE TITLE
Ошибка при получение списка лидов

### ISSUE THREAD

**Issue by Ahiles3005** [lptracker/php-sdk#4]
При запросе  "/lead/{id проекта}/list?offset=0&limit=1" появляется ошибка
`array(2) { ["status"]=> string(5) "error" ["errors"]=> array(1) { [0]=> array(2) { ["code"]=> int(500) ["message"]=> string(34) "Error: Undefined index: contact_id" } `

**Comment by sergeymakinen** [comment]
Было бы здорово увидеть минимальный кусок кода, где возникла ошибка, чтобы быстрее повторить и поправить. Спасибо.

**Comment by Ahiles3005** [comment]
стандартный кусок кода
`->getLeadsList($project, null, null, [], null, []) `
если вызываю так то отваливается.

Если добавить фильтр то все работает нормально. 
`getLeadsList($project, null, null, [], null, ['created_at_from'=>'1554336000']);`

500 ошибка, я почитал и понял что скорее всего проблема при обработке какого то лида на самом сервере, а библиотека тут не причем

**Comment by sergeymakinen** [comment]
Понял, спасибо, разберёмся.

**Comment by sergeymakinen** [comment]
Наконец-то дошли до этой задачи, должно быть исправлено.
