### ISSUE TITLE
нет funnelId, либо не корректный funnelId у лида

### ISSUE THREAD

**Issue by Ahiles3005** [lptracker/php-sdk#5]
/LPTracker/models/Lead.php 
тут ошибка 

```
        if (!empty($leadData['stage_id'])) {
            $this->funnelId = (int) $leadData['stage_id'];
        }
```

из за этого getFunnelId() возвращает не корректные данные

**Comment by sergeymakinen** [comment]
Здравствуйте! Наконец-то добрался до обновления апи и теперь `getFunnelId()` должна работать корректно (с версии 1.2.19).

**Comment by Ahiles3005** [comment]
чуть офтопну, проверьте owner так же

**Comment by sergeymakinen** [comment]
Когда чинил, тоже заметил, что не было данных и тоже починил.
Формат аналогичен тому, как устанавливается владелец: 0 — главный аккаунт или ID сотрудника.
