### ISSUE TITLE
Некоторые методы API не имеют параметра result в ответе

### ISSUE THREAD

**Issue by zlodes** [lptracker/php-sdk#6]
Получаем `ErrorException` `Undefined index: result` при попытке загрузить файл в лид или установить callback url (методы `addFileToLead` и `setProjectCallbackUrl`).

Достаём result, не проверив, есть ли он. https://github.com/lptracker/php-sdk/blob/master/src/LPTracker/LPTrackerRequest.php#L62

**Comment by zlodes** [comment]
Создал PR: #7

**Comment by sergeymakinen** [comment]
Спасибо! Смержил.
